### ISSUE TITLE
NullPointerException with null data in adapter

### ISSUE THREAD

**Issue by timothyjc** [danoz73/RecyclerViewFastScroller#17]
My data in my adapter is empty when the view is loaded and I get the following exception.

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
            at android.support.v7.widget.RecyclerView.getChildViewHolder(RecyclerView.java:2567)
            at xyz.danoz.recyclerviewfastscroller.calculation.progress.VerticalLinearLayoutManagerScrollProgressCalculator.calculateScrollProgress(VerticalLinearLayoutManagerScrollProgressCalculator.java:29)
            at xyz.danoz.recyclerviewfastscroller.AbsRecyclerViewFastScroller.onLayout(AbsRecyclerViewFastScroller.java:202)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)

The problem is in VerticalLinearLayoutManagerScrollProgressCalculator:

    @Override
    public float calculateScrollProgress(RecyclerView recyclerView) {
        LinearLayoutManager layoutManager = (LinearLayoutManager) recyclerView.getLayoutManager();
        int lastFullyVisiblePosition = layoutManager.findLastCompletelyVisibleItemPosition();

        View visibleChild = recyclerView.getChildAt(0);
        ViewHolder holder = recyclerView.getChildViewHolder(visibleChild);

There is no child at index 0.

This method should handle the case when the RecyclerView has no children, such as when there is not yet any data.

**Comment by Maxr1998** [comment]
Can confirm. This also applies when a using a filter with no results.

**Comment by Maxr1998** [comment]
Fixed in master, please close.

**Comment by Komoi** [comment]
It seems still broken to me - It fails with same (similar) stacktrace when trying to use it with empty filtered adapter. I am using your lib via compile 'xyz.danoz:recyclerviewfastscroller:0.1.0' in gradle.

**Comment by Maxr1998** [comment]
Use the new 0.1.1 and report back ;)

**Comment by Komoi** [comment]
This fixes the issue, thank you for fast response :)

**Comment by Maxr1998** [comment]
@Komoi may I ask you what you did because I still get a crash on fastScroller.setRecyclerView()
It's a nullpointer exception, but I'm pretty sure the items aren't null :/
Look at my source: https://github.com/Maxr1998/MaxLock/blob/master/app/src/main/java/de/Maxr1998/xposed/maxlock/ui/settings/appslist/AppsListFragment.java#L131

Layout: https://github.com/Maxr1998/MaxLock/blob/master/app/src/main/res/layout-v14/fragment_appslist.xml

Don't mind the outcommented lines, they are no comments in my local sources..

**Comment by Komoi** [comment]
I actually implemented fast scroll without indicator, it seemed to hard to implement if fully for me, I got lost in examples explaining use of indicators. Your problem seems unrelated to this issue and I really cant help you since I do not fully understand it. Good luck with your project :)

**Comment by Maxr1998** [comment]
Thanks for looking into it :)
I don't believe the section indicator is the problem, I think I'll have to rewrite this whole stuff anyway... 
Thanks and good luck for you too!

@danoz73 please close this issues as it's fixed.
